---
- name: create server_csr.json
  template:
    src: "{{ item }}"
    dest: "{{ ssl.cert.dir }}"
    owner: root
    group: root
    mode: 0640
  with_items:
   - server_csr.json 

- name: debug
  debug: msg="{{ ssl.cert.dir }}"

- name: ls
  shell: "ls {{ ssl.cert.dir }}/server_csr.json"

- name: create server cert 
  shell: "cd {{ ssl.cert.dir }} \
          && cfssl gencert --ca {{ ssl.cert.dir }}/ca.pem \
                           --ca-key {{ ssl.cert.dir }}/ca-key.pem \
                           --config {{ ssl.cert.dir }}/ca_profiles.json \
                           -profile=server \
                           {{ ssl.cert.dir }}/server_csr.json | cfssljson -bare server -"
