---
- name: install etcdctl
  include: install_etcdctl.yml

- name: test put key:test,value:thisistest
  shell: "export ETCDCTL_API=3; \
          etcdctl --endpoints={{ etcd.client.protocol }}://{{ host_ip }}:{{ etcd.client.port }} \
          --cacert={{ etcd.local.dir }}/ssl/ca.pem \
          --cert={{ etcd.local.dir }}/ssl/client.pem \
          --key={{ etcd.local.dir }}/ssl/client-key.pem \
          put /test 'thisistest'
         "

- name: test get key:test,value:thisistest
  shell: "export ETCDCTL_API=3; \
	  etcdctl --endpoints={{ etcd.client.protocol }}://{{ host_ip }}:{{ etcd.client.port }}  \
          --cacert={{ etcd.local.dir }}/ssl/ca.pem \
          --cert={{ etcd.local.dir }}/ssl/client.pem \
          --key={{ etcd.local.dir }}/ssl/client-key.pem \
          get /test
          "
  register: test_value

- name: show test value
  debug: msg="test:{{ test_value }}"

- name: test etcd endpoint health
  shell: "export ETCDCTL_API=3; \
          etcdctl --endpoints={{ etcd.client.protocol }}://{{ host_ip }}:{{ etcd.client.port }}  \
          --cacert={{ etcd.local.dir }}/ssl/ca.pem \
          --cert={{ etcd.local.dir }}/ssl/client.pem \
          --key={{ etcd.local.dir }}/ssl/client-key.pem \
          endpoint health
          "
  register: endpoint_health

- name: show endpoint health
  debug: msg="{{ endpoint_health }}"

- name: test etcd member list
  shell: "export ETCDCTL_API=3; \
          etcdctl --endpoints={{ etcd.client.protocol }}://{{ host_ip }}:{{ etcd.client.port }}  \ 
          --cacert={{ etcd.local.dir }}/ssl/ca.pem \
          --cert={{ etcd.local.dir }}/ssl/client.pem \
          --key={{ etcd.local.dir }}/ssl/client-key.pem \
          member list
          "
  register: member_list

- name: show member list
  debug: msg="{{ member_list }}"
