---
- name: "create {{ action }}_csr.json"
  template:
    src: "{{ item }}"
    dest: "{{ ssl_cert_dir }}/"
    owner: root
    group: root
    mode: 0640
  with_items:
   - "{{ action }}_csr.json"

- name: "create {{ action }} cert"
  shell: "cd {{ ssl_cert_dir }} \
          && cfssl gencert --ca {{ ssl_cert_dir }}/ca.pem \
                           --ca-key {{ ssl_cert_dir }}/ca-key.pem \
                           --config {{ ssl_cert_dir }}/ca_profiles.json \
                           -profile={{ action }} \
                           {{ ssl_cert_dir }}/{{ action }}_csr.json | cfssljson -bare {{ action }} -"
