---
- name: "Mkdir {{ app.ssl_dir }} "
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
   - "{{ app.ssl_dir }}"

- name: "copy cert from {{ ssl_cert_dir }} to {{ app.ssl_dir }}"
  copy:
    src: "{{ ssl_cert_dir }}/{{ item }}"
    dest: "{{ app.ssl_dir }}/" 
    owner: root
    group: root
    mode: 0640
  with_items: "{{ app.copy_certs }}"
